version: '3.4'

services:
  react-movies-api-net:
    image: ${DOCKER_REGISTRY-}reactmoviesapinet
    build:
      context: .
      dockerfile: react-movies-api-net/Dockerfile
    ports:
      - 8001:80
      - 8002:443
    depends_on:
      - "postgres"
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=FrancoPGSQL
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db_movies

volumes:
  postgres-data: